name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build and publish NuGet package
      run: |
        $Version = "$(echo $TAG_NAME | sed 's/^v//')";
        dotnet pack -c Release -o package /p:PackageVersion=$Version /p:Version=$Version;
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    - name: Push NuGet package to NuGet.org
      uses: nuget/push@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-source: 'https://api.nuget.org/v3/index.json'
        package: './package/*.nupkg'