name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build and publish NuGet package
      run: |
        $Version = "$(echo $TAG_NAME | sed 's/^v//')";
        dotnet pack -c Release -o package /p:PackageVersion=$Version /p:Version=$Version;
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    - name: Publish NuGet package to Nuget.org
      run: |
        nuget push ./package/*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey $NUGET_API_KEY
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}